version: "3.8"

services:
  ozone:
    image: apache/ozone:1.3.0
    container_name: ozone
    command: ozone-runner
    ports:
      - "9862:9862" # S3 Gateway
      - "9878:9878" # Ozone Manager UI
      - "9876:9876" # SCM UI
    volumes:
      - ozone-data:/data
    networks:
      - ozone-net

volumes:
  ozone-data:


networks:
  ozone-net:
